### PR TITLE
SQL Exercise committed

### PR DESCRIPTION
**Pull request by singharundeep18**
SQL and JDBC Exercises have been committed over here. Please review.

### CODE REVIEW

**Comment by saba83rish** [comment]
Arun please commit a .sql file under a java package in your project. I am not able to review .docx file. And that beats the purpose too.

**Comment by singharundeep18** [comment]
Sorry I just read your email. Thanks. I'll do it today!

**Comment by singharundeep18** [comment]
Good afternoon Sabarish,
I just submitted my SQL assignment. It is .sql file but it has all
questions that were before queries too. I wasn't sure if you wanted them in
separate file or same. So kept them in same.
Thanks.
Best Regards,
Arundeep Singh.

**Comment by singharundeep18** [comment]
And how should I submit the files that are in word document. I mean like
questions and stuff. Because I've JDBC and Threads assignments to push over
here.
Thanks.

**Comment by saba83rish** [comment]
doc files and question and answer types you can still email them. the sql queries and java code you can checkin via github

**Pull request merged**
